### ISSUE TITLE
[✨ Feature] Repository 동엽 파트

### ISSUE THREAD

**Issue by Yeop-Dong** [CharmRoom/CharmRoom#24]
## 기능 개요
> 추가하려는 기능에 대한 설명

레포지토리 맡은 파트 작성

## 상세 내용
> 작업할 내용 TODOLIST로 작성

아래 엔티티의 레포지토리 작성
- [x] User
- [x] Image
- [x] Point
- [x] Board
- [x] Comment
- [x] CommentLike
- [x] Attachment

## 참고(선택)
> 개발에 참고하였거나 함께 보면 좋을 페이지/자료

**Comment by Yeop-Dong** [comment]
~~정리~~

~~build.gradle에 추가 (DataJpaTest -> 인메모리 DB 사용 필요)~~
```

```

~~Entity User에 추가 (h2 DB는 user가 예약어)~~
```

```

**Comment by Yeop-Dong** [comment]
```src/test/resources```  폴더에
application-test.yml 을 추가합니다. 파일의 내용은 아래와 같습니다.
Test용으로 데이터베이스를 하나 더 만들어주세요

```YML
spring:
  application:
    name: charmroom
  datasource:
    url: jdbc:mysql://[DB 주소]:3306/[Test용 DB명]?serverTimezone=Asia/Seoul
    username: [DB ID]
    password: '[DB PW]'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 18081
```

Repository 단위 테스트시 상단 어노테이션에 다음을 추가합니다.

```Java
@DataJpaTest
@TestPropertySource(properties = {"spring.config.location = classpath:application-test.yml"})
@AutoConfigureTestDatabase(replace=AutoConfigureTestDatabase.Replace.NONE)
```

이 두가지 외에 이전에 공유했던 사항은 반영하지 않으시면 됩니다.
