### ISSUE TITLE
[✨ Feature] Service 동엽 파트

### ISSUE THREAD

**Issue by Yeop-Dong** [CharmRoom/CharmRoom#35]
## 기능 개요
> 추가하려는 기능에 대한 설명

Service 동엽 파트

## 상세 내용
> 작업할 내용 TODOLIST로 작성
- [x] User
- [x] Comment
- [x] CommentLike
- [x] Attachment
- [x] Board
- [x] Image
- [x] Point

## 참고(선택)
> 개발에 참고하였거나 함께 보면 좋을 페이지/자료

**Comment by Yeop-Dong** [comment]
viewController 현재 필요 없어서 제거하였습니다.

그리고 기존에 apicontroller 였던 패키지 이름을 바꿨습니다.
- 기존 (com.charmroom.charmroom.apicontroller)
- **변경 (com.charmroom.charmroom.controller.api)**

**Comment by Yeop-Dong** [comment]
[fix: Change exception package path](https://github.com/CharmRoom/CharmRoom/commit/fbac71532b1204bf33479f76bec71c18521a1440)
기존: com.charmroom.charmroom.controller.advice
변경: com.charmroom.charmroom.exception

**Comment by Yeop-Dong** [comment]
File Upload 관련 코드 작성 위해 공부 하다 보니

Image, Attachment 엔티티를 변경하게 됨
Image -> originalName(string) 추가
Attachment -> originalName(string) 추가

**Comment by Yeop-Dong** [comment]
비즈니스 로직에 사용할 component 추가
(com.charmrooom.charmroom.util.CharmroomUtil)
Nested 클래스로, 업로드에 필요한 component 추가
(com.charmroom.charmroom.util.CharmroomUtil.Upload)

이 컴포넌트에서 properties의 값을 가져와서 사용함
이 폴더는 runtime 중 자동으로 생성되고 삭제될 수 있으므로 
원래 사용하고 있던 폴더를 기입하지 말것.
- 추가될 프로퍼티 example(Windows 계열, yml)
```yml
charmroom:
  upload:
    image:
      path: C:\\ABC\\DEF\\image
    attachment:
      path: C:\\ABC\\DEF\\attachment
```

- 추가될 프로퍼티 example(Unix 계열, yml)
```yml
charmroom:
  upload:
    image:
      path: /abc/def/image
    attachment:
      path: /abc/def/attachment
```
